apiVersion: git.azuredevops.upbound.io/v1alpha1
kind: RepositoryFile
metadata:
  annotations:
    meta.upbound.io/example-id: git/v1alpha1/repositoryfile
    crossplane.io/external-name: d1/d2/.gitignore
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    branch: refs/heads/master
    commitMessage: First commit
    content: '**/*.tfstate'
    overwriteOnCreate: false
    repositoryIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: git.azuredevops.upbound.io/v1alpha1
kind: Repository
metadata:
  annotations:
    meta.upbound.io/example-id: git/v1alpha1/repositoryfile
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    initialization:
    - initType: Clean
    name: Example Git Repository
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azuredevops.upbound.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: git/v1alpha1/repositoryfile
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
